-- ============================================================
-- SNOWGUARD ALERT RESULTS TABLE
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS ALERT_RESULTS (
    ALERT_ID VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    ALERT_LEVEL VARCHAR,
    ALERT_TYPE VARCHAR,

    FEATURE_NAME VARCHAR,

    ALERT_MESSAGE VARCHAR,
    RECOMMENDATION VARCHAR,

    STATUS VARCHAR
);

SHOW TABLES;