-- ============================================================
-- SNOWGUARD ANALYTICS / MONITORING TABLE
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS MONITORING_SUMMARY (
    SUMMARY_ID VARCHAR,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    TOTAL_RECORDS INTEGER,

    QUALITY_SCORE FLOAT,
    QUALITY_STATUS VARCHAR,

    ANOMALY_COUNT INTEGER,
    ANOMALY_RATE FLOAT,

    DRIFTED_FEATURE_COUNT INTEGER,
    DRIFT_STATUS VARCHAR,

    RCA_COUNT INTEGER,

    OVERALL_STATUS VARCHAR
);

SHOW TABLES;