-- ============================================================
-- SNOWGUARD ANOMALY RESULTS TABLE
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA QUALITY;

CREATE TABLE IF NOT EXISTS ANOMALY_RESULTS (
    ANOMALY_ID VARCHAR,
    DETECTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    TRANSACTION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,

    AMOUNT FLOAT,
    INCOME FLOAT,
    AGE INTEGER,

    ANOMALY_SCORE FLOAT,
    ANOMALY_LABEL VARCHAR,
    SEVERITY VARCHAR,

    DETECTION_REASON VARCHAR
);

SHOW TABLES;