-- ============================================================
-- SNOWGUARD DRIFT DATA TABLES
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA PROCESSED;

CREATE TABLE IF NOT EXISTS TRANSACTIONS_REFERENCE (
    TRANSACTION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_DATE DATE,
    AGE INTEGER,
    INCOME FLOAT,
    AMOUNT FLOAT,
    CATEGORY VARCHAR,
    CITY VARCHAR,
    PAYMENT_METHOD VARCHAR
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS_CURRENT (
    TRANSACTION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_DATE DATE,
    AGE INTEGER,
    INCOME FLOAT,
    AMOUNT FLOAT,
    CATEGORY VARCHAR,
    CITY VARCHAR,
    PAYMENT_METHOD VARCHAR
);

SHOW TABLES;