-- ============================================================
-- SNOWGUARD DATA DRIFT RESULTS
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA QUALITY;

CREATE TABLE IF NOT EXISTS DRIFT_RESULTS (
    DRIFT_ID VARCHAR,
    DETECTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    DATASET_NAME VARCHAR,
    FEATURE_NAME VARCHAR,

    REFERENCE_RECORDS INTEGER,
    CURRENT_RECORDS INTEGER,

    REFERENCE_MEAN FLOAT,
    CURRENT_MEAN FLOAT,

    DRIFT_SCORE FLOAT,
    DRIFT_STATUS VARCHAR,

    DETECTION_METHOD VARCHAR,
    DETAILS VARCHAR
);

SHOW TABLES;