-- ============================================================
-- SNOWGUARD DATA QUALITY RESULTS
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA QUALITY;

CREATE TABLE IF NOT EXISTS QUALITY_RESULTS (
    CHECK_ID VARCHAR,
    CHECK_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    DATASET_NAME VARCHAR,
    CHECK_NAME VARCHAR,

    TOTAL_RECORDS INTEGER,
    AFFECTED_RECORDS INTEGER,

    QUALITY_SCORE FLOAT,
    STATUS VARCHAR,

    DETAILS VARCHAR
);

SHOW TABLES;