-- ============================================================
-- SNOWGUARD ROOT CAUSE ANALYSIS RESULTS
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS ROOT_CAUSE_RESULTS (
    RCA_ID VARCHAR,
    ANALYSIS_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    FEATURE_NAME VARCHAR,
    DIMENSION_NAME VARCHAR,
    DIMENSION_VALUE VARCHAR,

    REFERENCE_MEAN FLOAT,
    CURRENT_MEAN FLOAT,

    CHANGE_PERCENT FLOAT,

    CONTRIBUTION_PERCENT FLOAT,

    RCA_STATUS VARCHAR,
    DETAILS VARCHAR
);

SHOW TABLES;