-- ============================================================
-- SNOWGUARD RAW TRANSACTIONS TABLE
-- ============================================================

USE DATABASE SNOWGUARD_DB;

USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS TRANSACTIONS_RAW (
    TRANSACTION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TRANSACTION_DATE DATE,
    AGE INTEGER,
    INCOME FLOAT,
    AMOUNT FLOAT,
    CATEGORY VARCHAR,
    CITY VARCHAR,
    PAYMENT_METHOD VARCHAR,
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);